### ISSUE TITLE
[req] syshud-git AUR

### ISSUE THREAD

**Issue by kRHYME7** [System64fumo/syshud#12]
Hi, this will be helpful for users who wanted to switch releases to debug/contribute. Thanks!

**Comment by System64fumo** [comment]
Do you mean creating a seperate package on the aur?
The aur package is the *git* or *live* version
I don't have a concept of "Stable release"

Matter of fact i push out unfinished features to production (Real men test in production)

**Comment by kRHYME7** [comment]
Yup, I'm checking the PKGBUILD exactly right now.  Looks like It's not checking for versions, which shows it's not versioned.

But when I check the installed bin using the aur it's quite old. 
![image](https://github.com/user-attachments/assets/c3365595-5300-427f-998f-4e82890671cf)

I guess the package build  did not fetch it again, even triggering ` -Sy ` 

Also, by versioning convention it should be called ` syshud-git ` too.

**Comment by System64fumo** [comment]
Ah i see the problem, You have a cached version of the package on your system.
`rm -rf ~/.cache/yay/*`
then `yay -S syshud`

Personally i'm not really interested in adding versioning to the PKGBUILD
And to be quite frank with you i'm sort of cross with the AUR and the people behind it,
So i'm really not motivated enough to care about package conventions.

If it helps i'll see what i can do regarding some sort of fix for the cached package issue
But i doubt i can do much about it besides just spamming the PKGBUILD with a different number every time the package changes.

**Comment by kRHYME7** [comment]
>  If it helps i'll see what i can do regarding some sort of fix for the cached package issue
But i doubt i can do much about it besides just spamming the PKGBUILD with a different number every time the package changes.

Haha that's such a hassle,  you can make the `pkgver ` dynamic

example:
```
pkgver() {
  git -C Hyprland describe --long --tags | sed 's/^v//;s/\([^-]*-\)g/r\1/;s/-/./g'
}

```

but before getting that value, you might need to prep the package or whatever suits.   ` prepare () {...} ` or ` build() {... }`  



for now ` yay -Sc ` ` yay -Sy syshud ` works

**Comment by System64fumo** [comment]
Wouldn't doing things this way cause the package to remain outdated when searching for it on the AUR?
This would only apply post building/installation?
Unless i'm wrong?

You've used hyprland as an example.
It's version is tends to go out of date compared to what actually gets installed.

**Comment by kRHYME7** [comment]
> Wouldn't doing things this way cause the package to remain outdated when searching for it on the AUR?
This would only apply post building/installation?
Unless i'm wrong?

You're right and that is an intended outcome (there are some idiots flagging *-git packages as outdated lol).  *-git packages' PKGBUILD do not need to be updated. 
As the `pkgver` is dynamic. It is a convention to put *-git for packages that always fetch the upstream git repo.

**Comment by kRHYME7** [comment]
BTW this one is unrelated to this repo as this is not the AUR repo. I will close this for now.
