### ISSUE TITLE
doesn't respect gtk theme

### ISSUE THREAD

**Issue by littleblack111** [System64fumo/syshud#16]
from grep.app:
https://grep.app/search?q=%23include%20%3Cgtkmm
transmission uses gtkmm

it uses the theme bg and icon theme fine

but syshud doesnt:

transmission:
![Screenshot_2024-10-05-23-26-18](https://github.com/user-attachments/assets/371470fa-c6b3-4756-927a-862fa55aadf1)

syshud:
![Screenshot_2024-10-05-23-26-29](https://github.com/user-attachments/assets/8f6e2d7d-ba84-4ed9-83f5-7134c59b7b77)
![Screenshot_2024-10-05-23-26-37](https://github.com/user-attachments/assets/18ca51fd-88b1-412d-a073-dcc60d3ae13e)
![Screenshot_2024-10-05-23-26-45](https://github.com/user-attachments/assets/0510911f-190b-41e5-adfd-777992631e86)

**Comment by System64fumo** [comment]
syshud uses your default GTK 4 theme as a base but can be customized with custom css
The default custom css is located in /usr/share/sys64/hud/style.css

Copy it to ~/.config/sys64/hud/style.css then remove this line right here https://github.com/System64fumo/syshud/blob/main/style.css#L6

Or change it to another GTK defined color e.g: @theme_base_color

**Comment by littleblack111** [comment]
i know.. but it doesnt seem to work... the icon is definatly off...
![Screenshot_2024-10-06-21-06-52](https://github.com/user-attachments/assets/d9d79928-a9b2-468e-8295-cc12810d2430)
thunar icons

u can see the difference

**Comment by System64fumo** [comment]
The icons used in syshud are symbolic (monochrome)
I think you're talking about the microphone being colored while the speakers are not?

It could be that your theme lacks symbolic icons for the microphone icon.

**Comment by littleblack111** [comment]
i remember digging into the code and figuring which file did it use. I tried to ln -s and cp it with the proper name of it but didn't work...

**Comment by System64fumo** [comment]
No idea, I personally use [Colloid icon theme](https://github.com/vinceliuice/Colloid-icon-theme) i've tested papirus too and that also works fine.

I'm gonna close this since this seems like a theming issue on your end.
I'd just recomment using an icon theme that has more icons or more icon names.

**Comment by littleblack111** [comment]
hmm

it seems like my theme does have the icons specified in `window.cpp`:
```
./actions/scalable/audio-volume-high-symbolic-dark.svg
./actions/scalable/audio-volume-high.svg
./actions/scalable/audio-volume-low-symbolic-dark.svg
./actions/scalable/audio-volume-low-symbolic.symbolic.svg
./actions/scalable/audio-volume-low.svg
./actions/scalable/audio-volume-medium-symbolic-dark.svg
./actions/scalable/audio-volume-medium.svg
./actions/scalable/audio-volume-muted-blocked-panel.svg
./actions/scalable/audio-volume-muted-blocking-panel.svg
./actions/scalable/audio-volume-muted-blocking-symbolic.svg
./actions/scalable/audio-volume-muted-blocking.svg
./actions/scalable/audio-volume-muted-symbolic-dark.svg
./actions/scalable/audio-volume-muted-symbolic.symbolic.svg
./actions/scalable/audio-volume-muted.svg
./actions/scalable/audio-volume-off-symbolic.svg
./actions/scalable/audio-volume-overamplified-symbolic.svg
./actions/scalable/audio-volume-overamplified-symbolic.symbolic.svg
./actions/scalable/audio-volume-overamplified.svg
./actions/scalable/audio-volume-zero-panel.svg
./actions/scalable/audio-volume-high-panel.svg
./actions/scalable/audio-volume-high-symbolic.svg
./actions/scalable/audio-volume-low-panel.svg
./actions/scalable/audio-volume-low-symbolic.svg
./actions/scalable/audio-volume-low-zero-panel.svg
./actions/scalable/audio-volume-low-zero.svg
./actions/scalable/audio-volume-medium-panel.svg
./actions/scalable/audio-volume-medium-symbolic.svg
./actions/scalable/audio-volume-muted-panel.svg
./actions/scalable/audio-volume-muted-symbolic.svg
./actions/scalable/audio-volume-off.svg
./devices/scalable/audio-volume-off-symbolic-dark.svg
./devices/scalable/audio-volume-off-symbolic.svg
```

in main.cpp:
```
	std::map<int, std::string> value_levels = {
		{0, "muted"},
		{1, "low"},
		{2, "medium"},
		{3, "high"},
	};


		if (muted)
			icon = "audio-volume-muted-blocking-symbolic";
		else if (value <= 100)
			icon = "audio-volume-" + value_levels[value / 34 + 1] + "-symbolic";
		else
			icon = "audio-volume-overamplified-symbolic";
```

**Comment by littleblack111** [comment]
![Screenshot_2024-10-27-10-51-24](https://github.com/user-attachments/assets/f0da950b-f492-4661-a5c4-e54eab682094)
such as this vs what is showin in syshud:
![Screenshot_2024-10-27-10-51-39](https://github.com/user-attachments/assets/defa8c94-dca8-42d9-aab6-b37e794bf400)

**Comment by System64fumo** [comment]
But you do have them?

**Comment by System64fumo** [comment]
Okay?
So then where's the issue?
syshud uses *symbolic* icons
So black and white variants of what you're expecting

For the microphone one that may be a lack of symbolic mic icon set issue
