### ISSUE TITLE
crash after update

### ISSUE THREAD

**Issue by littleblack111** [System64fumo/syshud#18]
updated stuff, then syshud:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
[1]    683553 IOT instruction (core dumped)  syshud
```

**Comment by System64fumo** [comment]
Yup known issue
Documented in the commit of the same update (Sorry!)
https://github.com/System64fumo/syshud/commit/f599b2a594eda7b39a9742523866bea0dbfee634

**Comment by System64fumo** [comment]
No problem, This is still technically a bug since the default config *should* be loaded as a placeholder but it seems like it's not therefore null settings are being read..

I'll roll out a fix for syshud and sysbar eventually so this won't ever happen again.

**Comment by System64fumo** [comment]
After procrastinating for the whole day i've gotten around to actually fixing this.
The issue was already marked as closed (which fair enough) but now it's officially fixed™
