### ISSUE TITLE
Slider width small even though set to bigger number in config file

### ISSUE THREAD

**Issue by BTD12SA** [System64fumo/syshud#19]
### Description
Width in config is set to 500 but slider appears tiny in actuality

### To Reproduce
download syshud package from aur launch it and try to change volume, volume slider appears tiny

### System Info
Arch linux
Hyprland v0.45.0
Syshud v2024.11.04-1 (according to AUR package)
Kernel 6.11.6-arch1-1

### Video of the issue
https://github.com/user-attachments/assets/62e3ab34-8e0e-4d97-8923-88d49d5703ab

**Comment by System64fumo** [comment]
Huh you're right.
Some update broke this by the looks of it because vertical layouts seem to work fine on my phone but not my desktop..
Will check this out in a bit.

**Comment by BTD12SA** [comment]
That was pretty quick!

And yes that fixed it, Thanks!
