### ISSUE TITLE
Volume lower than 25% will present a icon of muted

### ISSUE THREAD

**Issue by vollowx** [System64fumo/syshud#6]
![img](https://github.com/System64fumo/syshud/assets/73375859/237268dc-e231-4db8-ab40-7d81b5b65ecd)

I guess it's [this line](https://github.com/System64fumo/syshud/blob/main/src/window.cpp#L216), `(25 - 1) / 25 = 0` in C++, and the index `0` refers to the [muted icon](https://github.com/System64fumo/syshud/blob/main/src/window.cpp#L183), and IMO the expression `((value - 1) / 25) + 1` is fine.

Besides, it might be better if you separate the muted icon and others. However, I also noticed the `audio-volume-muted-blocking-symbolic` and `audio-volume-muted-symbolic`, I don't know the difference, at least they look the same using the default Adwaita icon pack.

**Comment by System64fumo** [comment]
Yeah.. i was sorta aware this would happen, My icon theme represents this icon as an empty volume icon without the mute line however it seems like other icon themes might represent it differently.
I'll roll out a quick fix in a few minutes.

**Comment by System64fumo** [comment]
Should be good now.
