### ISSUE TITLE
muted mic/speaker affect brightness css config

### ISSUE THREAD

**Issue by shadowelite-sec** [System64fumo/syshud#8]
When I mute the mic or speaker, it also affects the brightness CSS

https://github.com/user-attachments/assets/2c8be40d-6ddf-46bf-83d5-58ca065c0f76

also noticed mute color not appying when volume of  `mic/speaker > 100` 

https://github.com/user-attachments/assets/f14b8344-b19f-4cfc-a1e1-be6c8851fb91

**Comment by System64fumo** [comment]
Ill take a look at this tomorrow, Sounds like an easy fix (I'm totally jinxing myself by saying this)

**Comment by shadowelite-sec** [comment]
> Ill take a look at this tomorrow, Sounds like an easy fix (I'm totally jinxing myself by saying this)

Sure 😊 👍

**Comment by System64fumo** [comment]
@shadowelite-sec Sorry for keeping you waiting, Should be fixed now let me know.

**Comment by shadowelite-sec** [comment]
Working thanks
